CREATE TABLE spatial_ref_sys(srid INTEGER PRIMARY KEY,sr_name TEXT, auth_name TEXT,auth_srid INTEGER,srtext TEXT,sr_xytol REAL,sr_ztol REAL );
CREATE TABLE geometry_columns (f_table_name TEXT,f_geometry_column TEXT,geometry_type INTEGER,geometry_dettype INTEGER,coord_dimension INTEGER,srid INTEGER,geometry_format TEXT);
CREATE TABLE TB_DOMAIN (ID INTEGER PRIMARY KEY not null, ACTIVE INTEGER(1) default 1 not null, CAPTION VARCHAR2(255) not null, READ_ONLY INTEGER(1) default 0 not null, TABLE_DOES_NOT_EXIST INTEGER(1) default 0 not null, TABLE_NAME VARCHAR2(30) not null, constraint TB_DOMAIN_CAPTION_U unique (CAPTION), constraint TB_DOMAIN_TABLENAME_U unique (TABLE_NAME));
CREATE TABLE TB_INFO (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(255), PARAM VARCHAR2(255) not null, VALUE_CHAR VARCHAR2(255), VALUE_NUMBER REAL(20,8), constraint TB_INFO_U unique (PARAM));
CREATE TABLE TB_VERSION (ID INTEGER PRIMARY KEY not null, DATA_MODEL_CODE VARCHAR2(12), MODULE_NAME VARCHAR2(255), VERSION_DATE DATETIME_as_text not null, VERSION_NUMBER VARCHAR2(10) not null, CAPTION VARCHAR2(255), MIN_VERSION_REASON VARCHAR2(4000), MIN_VERSION VARCHAR2(10));
CREATE TABLE fdo_columns( f_table_name TEXT, f_column_name TEXT, f_column_desc TEXT, fdo_data_type INTEGER, fdo_data_details INTEGER, fdo_data_length INTEGER, fdo_data_precision INTEGER, fdo_data_scale INTEGER);
CREATE TABLE TB_SEQUENCE_EMULATION (SEQUENCE_NAME text, NEXT_VALUE integer, constraint TB_SEQUENCE_EMULATION_P primary key (SEQUENCE_NAME));
CREATE TABLE TB_ATTRIBUTE (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, DESCRIPTION VARCHAR2(4000), F_CLASS_ID INTEGER(10) not null, IS_SYSTEM INTEGER(1) default 0 not null, NAME VARCHAR2(30) not null, UNIT_ID INTEGER(18), constraint TB_ATTRIBUTE_NAME_U unique (F_CLASS_ID, NAME));
CREATE TABLE TB_COLUMN_MAPPING (ID INTEGER PRIMARY KEY not null, ID_TABLE INTEGER(18) not null, IS_CHANGEABLE INTEGER(1) default 1 not null, MAPPING_COLUMN VARCHAR2(255) not null, TB_COLUMN VARCHAR2(255) not null);
CREATE TABLE TB_COMPOUND (ID INTEGER PRIMARY KEY not null, CHILD_F_CLASS_ID INTEGER(10) not null, PARENT_F_CLASS_ID INTEGER(10) not null);
CREATE TABLE TB_DATACHECK (ID INTEGER PRIMARY KEY not null, CHECK_STMT VARCHAR2(4000), DESCRIPTION VARCHAR2(255), NAME VARCHAR2(255), PARENT_ID INTEGER(18) default -1 not null, SELECT_ON_TRIGGER INTEGER(1) default 0 not null, WITHOUT_RLS INTEGER(1) default 0 not null, ACTIVE INTEGER(1) default 1 not null, MODULE_NAME VARCHAR2(255));
CREATE TABLE TB_DATAMODELCODE (ID INTEGER PRIMARY KEY not null, DATA_MODEL_CODE VARCHAR2(12));
CREATE TABLE TB_DD_LOG (ID INTEGER PRIMARY KEY not null, EXEC_USER VARCHAR2(255), EXECUTE_TIME DATETIME_as_text, SQL_STATEMENT VARCHAR2(4000));
CREATE TABLE TB_DICTIONARY (F_CLASS_ID INTEGER PRIMARY KEY not null, ACTIVE INTEGER(1) default 1 not null, CAPTION VARCHAR2(255) not null, DIMENSION INTEGER(1) default 2 not null, F_CLASS_NAME VARCHAR2(30) not null, F_CLASS_TYPE VARCHAR2(1) not null, FEATURE_REPRESENTATION VARCHAR2(255), MAX_X REAL(20,8) default 1000000 not null, MAX_Y REAL(20,8) default 1000000 not null, MAX_Z REAL(20,8) default 1000000 not null, MIN_X REAL(20,8) default -10 not null, MIN_Y REAL(20,8) default -10 not null, MIN_Z REAL(20,8) default -10 not null, MODEL_F_CLASS_ID INTEGER(10), PARENT_F_CLASS_ID INTEGER(10), READ_ONLY INTEGER(1) default 0 not null, SPATIAL_RELATE VARCHAR2(4000) default 'anyinteract' not null, SRID INTEGER(18) default 0 not null, TABLE_DOES_NOT_EXIST INTEGER(1) default 0 not null, TOLERANCE REAL(20,8) default 0.005 not null, TOPIC_ID INTEGER(18) not null, USER_DEFINED_ELEVATION INTEGER(1) default 0 not null, USER_DEFINED_ORIENTATION INTEGER(1) default 0 not null, VERSION_ENABLED INTEGER(1) default 0, constraint TB_DICTIONARY_FCNAME_U unique (F_CLASS_NAME));
CREATE TABLE TB_DIMENSION (ID INTEGER PRIMARY KEY not null, ABSCISSA_DIM_LABEL_DEF_ID INTEGER(18), ABSCISSA_END_LABEL_DEF_ID INTEGER(18), ABSCISSA_START_LABEL_DEF_ID INTEGER(18), ALIGNED_DIM_LABEL_DEF_ID INTEGER(18), AUTO_ABSCISSA_END INTEGER(1), AUTO_ABSCISSA_START INTEGER(1), DIMENSION_F_CLASS_ID INTEGER(10) not null, LABEL_F_CLASS_ID INTEGER(10) not null, LINE_F_CLASS_ID INTEGER(10) not null, ORDINATE_DIM_LABEL_DEF_ID INTEGER(18), POINT_F_CLASS_ID INTEGER(10) not null);
CREATE TABLE TB_ERROR_LOG (ID INTEGER PRIMARY KEY not null, ERROR_TEXT VARCHAR2(4000) not null, ERROR_TIME TIMESTAMP_as_text(6), F_CLASS_ID INTEGER(10), FID INTEGER(10), FID_DESCRIPTION VARCHAR2(255), MODULE_NAME VARCHAR2(255));
CREATE TABLE TB_EXPLORER_CAT_TYPE (ID INTEGER PRIMARY KEY not null, CATEGORY_ID INTEGER(18) not null, TYPE_NAME VARCHAR2(255) not null);
CREATE TABLE TB_EXPLORER_CATEGORY (ID INTEGER PRIMARY KEY not null, CATEGORY_ID INTEGER(18), DESKTOP_ICON VARCHAR2(255), EXPANDED INTEGER(1) default 0 not null, NAME VARCHAR2(255), WEB_ICON VARCHAR2(255));
CREATE TABLE TB_EXPLORER_DEF (ID INTEGER PRIMARY KEY not null, NAME VARCHAR2(255), PRIORITY INTEGER(2) default 0 not null, constraint TB_EXPLORER_DEF_NAME_U unique (NAME));
CREATE TABLE TB_EXPLORER_DEF_STMT (ID INTEGER PRIMARY KEY not null, DEF_ID INTEGER(18) not null, PRIORITY INTEGER(2) default 0 not null, STMT_ID INTEGER(18) not null);
CREATE TABLE TB_EXPLORER_GROUP (ID INTEGER PRIMARY KEY not null, GROUP_ID INTEGER(18), NAME VARCHAR2(255), constraint TB_EXPLORER_GROUP_NAME_U unique (NAME));
CREATE TABLE TB_EXPLORER_GROUP_DEF (ID INTEGER PRIMARY KEY not null, DEF_ID INTEGER(18) not null, GROUP_ID INTEGER(18) not null, PRIORITY INTEGER(2) default 0 not null);
CREATE TABLE TB_EXPLORER_GROUP_UG_RESTR (ID INTEGER PRIMARY KEY not null, EXPLORER_GROUP_ID INTEGER(18), USERGROUP_ID VARCHAR2(36));
CREATE TABLE TB_EXPLORER_ITEM (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255), CATEGORY_ID INTEGER(18), GROUP_DEF_ID INTEGER(18) not null, KEY VARCHAR2(255), NAME VARCHAR2(255), NODETYPES VARCHAR2(255), STMT_ID INTEGER(18), USER_ID VARCHAR2(36), WHERECLAUSE VARCHAR2(4000));
CREATE TABLE TB_EXPLORER_NODE_TYPE (ID INTEGER PRIMARY KEY not null, DESIGNER VARCHAR2(255), NAME VARCHAR2(255), PARENT_NODE_TYPE_NAME VARCHAR2(255), constraint TB_EXPLORER_NODE_TYPE_NAME_U unique (NAME));
CREATE TABLE TB_EXPLORER_STMT (ID INTEGER PRIMARY KEY not null, ACTIVE INTEGER(1) default 1 not null, CATEGORY_ID INTEGER(18), DESIGNER VARCHAR2(255), DESKTOP_ICON VARCHAR2(255), DRAW_ALL_RECORDS INTEGER(1) default 0 not null, EXPANDED INTEGER(1) default 0 not null, ITEM_NAME VARCHAR2(255), NAME VARCHAR2(255), PRIORITY INTEGER(2) default 0 not null, SEARCH_ATTR_NAME VARCHAR2(255), SELECT_STMT VARCHAR2(4000) not null, WEB_ICON VARCHAR2(255));
CREATE TABLE TB_EXPLORER_STMT_STMT (ID INTEGER PRIMARY KEY not null, CHILD_STMT_ID INTEGER(18) not null, PARENT_STMT_ID INTEGER(18) not null);
CREATE TABLE TB_EXPLORER_STMT_TYPE (ID INTEGER PRIMARY KEY not null, STMT_ID INTEGER(18) not null, TYPE_NAME VARCHAR2(255) not null);
CREATE TABLE TB_FCONT_FC_PROFILE_RESTR (ID INTEGER PRIMARY KEY not null, FCONT_ID INTEGER(18) not null, FCONT_PROFILE_ID INTEGER(18) not null);
CREATE TABLE TB_FCONT_MENU_ITEM (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, FCONT_ID INTEGER(18) not null, IMAGE VARCHAR2(255), KEY VARCHAR2(255) not null, TOOLTIP VARCHAR2(4000), TYPE VARCHAR2(255));
CREATE INDEX TB_FCONT_MENU_ITEM_IX1 on TB_FCONT_MENU_ITEM (FCONT_ID);
CREATE TABLE TB_FCONT_MENU_ITEM_UG_RESTR (ID INTEGER PRIMARY KEY not null, FCONT_MENU_ITEM_ID INTEGER(18) not null, USERGROUP_ID VARCHAR2(40) not null);
CREATE INDEX TB_FCONT_MENU_ITEM_UG_REST_IX1 on TB_FCONT_MENU_ITEM_UG_RESTR (FCONT_MENU_ITEM_ID);
CREATE TABLE TB_FCONT_PROFILE (ID INTEGER PRIMARY KEY not null, NAME VARCHAR2(255));
CREATE TABLE TB_FCONT_PROFILE_UG_RESTR (ID INTEGER PRIMARY KEY not null, FCONT_PROFILE_ID INTEGER(18) not null, USERGROUP_ID VARCHAR2(40) not null);
CREATE TABLE TB_FUNCTIONALITEM_FILTER (ID VARCHAR2(36) not null, FUNCTION_ID VARCHAR2(36) not null, USERGROUP_ID VARCHAR2(36) not null, constraint TB_FUNCTIONALITEM_FILTER_P primary key (ID));
CREATE TABLE TB_JOB (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(4000), DATE_CREATED DATETIME_as_text default current_date not null, IS_LOCKED INTEGER(1) default 0 not null, JOB_TEMPLATE_ID INTEGER(18), NAME VARCHAR2(255) not null, USE_STATE INTEGER(2) default 0 not null, USER_CREATED VARCHAR2(255) not null, constraint TB_JOB_NAME_U unique (NAME));
CREATE TABLE TB_JOB_DICTIONARY (ID INTEGER PRIMARY KEY not null, BUFFER REAL(20,8) default 0.005, F_CLASS_ID INTEGER(10) not null, FEATURE_LOCKING_TYPE VARCHAR2(1) default 'O' not null, PERIMETER_F_CLASS_ID INTEGER(10), constraint TB_JOB_DICTIONARY_FCID_U unique (F_CLASS_ID));
CREATE TABLE TB_JOB_FCLASS (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10) not null, JOB_TOPIC_ID INTEGER(18) not null);
CREATE INDEX TB_JOB_FCLASS_JT_ID on TB_JOB_FCLASS (JOB_TOPIC_ID);
CREATE TABLE TB_JOB_PERIMETER (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10), GEOM FDO_GEOMETRY_as_blob, IS_NOT_BUFFERED INTEGER(1), JOB_ID INTEGER(18) not null, JOB_PERIMETER_TYPE_ID INTEGER(18) not null, TOPO_ID INTEGER(18));
CREATE TABLE TB_JOB_PERIMETER_TYPE (ID INTEGER PRIMARY KEY not null, DESCRIPTION VARCHAR2(4000), NAME VARCHAR2(255) not null, constraint TB_JOB_PERIMETER_TYPE_NAME_U unique (NAME));
CREATE TABLE TB_JOB_STATE (ID INTEGER PRIMARY KEY not null, DESCRIPTION VARCHAR2(4000), FEATURES_EDITABLE INTEGER(1) not null, INITIAL_STATE INTEGER(1) not null, NAME VARCHAR2(255) not null, USE_JOBID INTEGER(1) not null, constraint TB_JOB_STATE_NAME_U unique (NAME));
CREATE TABLE TB_JOB_STATE_TRANSITION (ID INTEGER PRIMARY KEY not null, PASSWORD VARCHAR2(255), PREDECESSOR_ID INTEGER(18) not null, SUCCESSOR_ID INTEGER(18) not null, TRANSITION_DIRECTION VARCHAR2(1) not null, TRANSITION_TYPE VARCHAR2(1) not null);
CREATE TABLE TB_JOB_TEMPLATE (ID INTEGER PRIMARY KEY not null, NAME VARCHAR2(255) not null, constraint TB_JOB_TEMPLATE_NAME_U unique (NAME));
CREATE TABLE TB_JOB_TEMPLATE_DEF (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10) not null, JOB_TEMPLATE_ID INTEGER(18) not null);
CREATE TABLE TB_JOB_TEMPLATE_UG_RESTR (ID INTEGER PRIMARY KEY not null, JOB_TEMPLATE_ID INTEGER(18), USER_GROUP_ID VARCHAR2(255));
CREATE TABLE TB_JOB_TOPIC (ID INTEGER PRIMARY KEY not null, JOB_ID INTEGER(18) not null, TOPIC_ID INTEGER(18) not null);
CREATE INDEX TB_JOB_TOPIC_JOB_ID on TB_JOB_TOPIC (JOB_ID);
CREATE INDEX TB_JOB_TOPIC_TOPIC_ID on TB_JOB_TOPIC (TOPIC_ID);
CREATE TABLE TB_JOB_TOPIC_STATE (ID INTEGER PRIMARY KEY not null, DATE_UPDATED DATETIME_as_text, JOB_STATE_ID INTEGER(18) not null, JOB_TOPIC_ID INTEGER(18) not null, SELECTED INTEGER(1) not null, USER_UPDATED VARCHAR2(255));
CREATE INDEX TB_JOB_TOPIC_STATE_JT_ID on TB_JOB_TOPIC_STATE (JOB_TOPIC_ID);
CREATE TABLE TB_JOB_VERSION (JOB_VERSION INTEGER PRIMARY KEY not null, CONFLICT INTEGER(1), EXPIRATION_DATE DATETIME_as_text, FID INTEGER(10) not null, JOB_ID INTEGER(18) default 0 not null, JOB_OLD_VERSION INTEGER(10) not null, JOB_OPERATION_ID INTEGER(10) default -1 not null, OPERATION_DATE DATETIME_as_text, OS_USER_NAME VARCHAR2(255), STATE INTEGER(2) not null);
CREATE INDEX TB_JOB_VERSION_IDX1 on TB_JOB_VERSION (FID);
CREATE INDEX TB_JOB_VERSION_IDX2 on TB_JOB_VERSION (JOB_OLD_VERSION);
CREATE INDEX TB_JOB_VERSION_IDX3 on TB_JOB_VERSION (JOB_ID);
CREATE INDEX TB_JOB_VERSION_IDX4 on TB_JOB_VERSION (JOB_VERSION, JOB_ID);
CREATE TABLE TB_LABEL (ID INTEGER PRIMARY KEY not null, PARENT_F_CLASS_ID INTEGER(10) not null, TBL_F_CLASS_ID INTEGER(10) not null, constraint TB_LABEL_TBL_U unique (TBL_F_CLASS_ID), constraint TB_LABEL_U unique (PARENT_F_CLASS_ID));
CREATE TABLE TB_LABEL_DEF (ID INTEGER PRIMARY KEY not null, ABSOLUTE_OFFSET_X REAL(20,8), ABSOLUTE_OFFSET_Y REAL(20,8), ACTIVE INTEGER(1) default 1 not null, AUTO_LABEL INTEGER(1), DTEXT INTEGER(1), EXAMPLE VARCHAR2(255), HORIZONTAL_ALIGNMENT VARCHAR2(10) default 'Left' not null, IS_RELATIVE_ORIENTATION INTEGER(1) default 1 not null, LABEL_ID INTEGER(18) not null, NAME VARCHAR2(255) not null, ORIENTATION REAL(20,8) default 0 not null, OVERWRITE_LABEL_TEXT_WITH_NULL INTEGER(1), POSITION_ALONG_OBJECT INTEGER(1) default 2 not null, PRE VARCHAR2(255), RELATIVE_OFFSET_X REAL(20,8), RELATIVE_OFFSET_Y REAL(20,8), SCALE INTEGER(1), SCALE_SELECT_STATEMENT VARCHAR2(2000), SELECT_STATEMENT VARCHAR2(2000) not null, SELECT_STATEMENT_GEOMETRY VARCHAR2(4000) default 'select FID, geom from [parent] where fid = (select [FID_parent] from [FeatureClass] where FID = ?)', SUF VARCHAR2(255), TEXT_READABLE_ON_LAYOUT INTEGER(1) default 1 not null, USER_SELECTS_POSITION INTEGER(1), VERTICAL_ALIGNMENT VARCHAR2(10) default 'Baseline' not null);
CREATE TABLE TB_LOCATION_DEF (ID INTEGER PRIMARY KEY not null, F_CLASS_ID_COLLECTION INTEGER(10), F_CLASS_ID_LINE INTEGER(10) not null, F_CLASS_ID_POINT INTEGER(10) not null, F_CLASS_ID_POLYGON INTEGER(10), NAME VARCHAR2(255) not null, constraint TB_LOCATION_DEF_NAME unique (NAME));
CREATE TABLE TB_NET_RESULT (ID INTEGER PRIMARY KEY not null, CLOSING INTEGER(1), ELEMENT_TYPE INTEGER(1), FID_GEOM INTEGER(10), GEOM_FC_ID INTEGER(10), LINK_ID REAL, PATH_ID REAL, PREV_ELEMENT_ID INTEGER(18), SEQ_NO REAL);
CREATE INDEX TB_NET_RESULT_I on TB_NET_RESULT (PATH_ID);
CREATE INDEX TB_NET_RESULT_I1 on TB_NET_RESULT (LINK_ID);
CREATE TABLE TB_NET_SCOND (ID INTEGER PRIMARY KEY not null, ID_NET_SCOND_DEF INTEGER(18), ID_NET_TRACE_TPL INTEGER(18));
CREATE TABLE TB_NET_SCOND_DEF (ID INTEGER PRIMARY KEY not null, ACTIVE INTEGER(1), COMMENTARY VARCHAR2(255), IS_COST INTEGER(1) not null, NAME VARCHAR2(255), SQL_STMT VARCHAR2(2000), TOPO_TYPE INTEGER(1) not null, TOPOLOGY_ID INTEGER(18));
CREATE TABLE TB_NET_TRACE_TPL (ID INTEGER PRIMARY KEY not null, ACTION INTEGER(1), ACTIVE INTEGER(1), COMMENTARY VARCHAR2(255), DIRECTION INTEGER(1), NAME VARCHAR2(255), TOPOLOGY_ID INTEGER(18), TRACE_TYPE INTEGER(2));
CREATE TABLE TB_OFFICE (ID INTEGER PRIMARY KEY not null, NAME VARCHAR2(255) not null);
CREATE TABLE TB_OPERATION_LOG (ID INTEGER PRIMARY KEY not null, FID INTEGER(10), JOB_ID INTEGER(18), NEW_FID_1 INTEGER(10), NEW_FID_2 INTEGER(10), OPERATION_ID INTEGER(10), X REAL(20,8), Y REAL(20,8), Z REAL(20,8));
CREATE INDEX TB_OPERATION_LOG_IDX1 on TB_OPERATION_LOG (FID);
CREATE TABLE TB_PERIMETER (ID INTEGER PRIMARY KEY not null, GEOM FDO_GEOMETRY_as_blob);
CREATE TABLE TB_POINTNUMBER_GROUP (ID INTEGER PRIMARY KEY not null, GENERIC VARCHAR2(1000), NAME VARCHAR2(255), RANGEMAX INTEGER(10), RANGEMIN INTEGER(10));
CREATE TABLE TB_POINTNUMBER_GROUP_DICT (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10) not null, PNGROUP_ID INTEGER(18) not null, constraint TB_POINTNUMBER_GR_DICT_U unique (F_CLASS_ID));
CREATE TABLE TB_POINTNUMBER_INCREMENT (ID INTEGER PRIMARY KEY not null, NEXTVAL INTEGER(18) not null, PNGROUP_ID INTEGER(18) not null, PREFIX VARCHAR2(20) not null);
CREATE INDEX TB_POINTNUMBER_INCREMENT_IDX on TB_POINTNUMBER_INCREMENT (PNGROUP_ID, PREFIX);
CREATE TABLE TB_POSITION_FINDER (ID INTEGER PRIMARY KEY not null, ADDITIONAL_WHERE_CLAUSE VARCHAR2(4000), GEOM_COLUMN VARCHAR2(30), GEOM_STMT_1 VARCHAR2(4000), GEOM_STMT_2 VARCHAR2(4000), GEOM_STMT_3 VARCHAR2(4000), GEOM_STMT_4 VARCHAR2(4000), GUITYPE INTEGER(2) default 1 not null, INPUT_COLUMN_1 VARCHAR2(30), INPUT_COLUMN_2 VARCHAR2(30), INPUT_COLUMN_3 VARCHAR2(30), INPUT_COLUMN_4 VARCHAR2(30), INPUT_COLUMN_5 VARCHAR2(30), INPUTTYPE_1 INTEGER(2) default 1 not null, INPUTTYPE_2 INTEGER(2) default 1 not null, INPUTTYPE_3 INTEGER(2) default 1 not null, INPUTTYPE_4 INTEGER(2) default 1 not null, NAME VARCHAR2(100), NOTFOUND_MSG_1 VARCHAR2(255), NOTFOUND_MSG_2 VARCHAR2(255), NOTFOUND_MSG_3 VARCHAR2(255), NOTFOUND_MSG_4 VARCHAR2(255), ORDER_COLUMN VARCHAR2(100), PK_COLUMN VARCHAR2(30), PRIORITY INTEGER(3) default 0 not null, SELECT_STMT_1 VARCHAR2(4000), SELECT_STMT_2 VARCHAR2(4000), SELECT_STMT_3 VARCHAR2(4000), SELECT_STMT_4 VARCHAR2(4000), STMT_TITLE_1 VARCHAR2(100), STMT_TITLE_2 VARCHAR2(100), STMT_TITLE_3 VARCHAR2(100), STMT_TITLE_4 VARCHAR2(100), STMT_TITLE_5 VARCHAR2(100), TABLE_NAME VARCHAR2(30), constraint TB_POSITION_FINDER_NAME_U unique (NAME));
CREATE TABLE TB_REF (ID INTEGER PRIMARY KEY not null, IS_PUBLIC INTEGER(1) default 0 not null, REF_NAME VARCHAR2(255) not null, SET_LAST_VALUE INTEGER(1) default 0 not null, TABLE_NAME VARCHAR2(30) not null, USER_ID VARCHAR2(40));
CREATE INDEX TB_REF_IX1 on TB_REF (TABLE_NAME);
CREATE TABLE TB_REF_FLD (ID INTEGER PRIMARY KEY not null, FIELD_NAME VARCHAR2(30) not null, FIELD_VALUE VARCHAR2(4000), REF_ID INTEGER(18) not null);
CREATE INDEX TB_REF_FLD_IX1 on TB_REF_FLD (REF_ID);
CREATE TABLE TB_REF_SELECT (ID INTEGER PRIMARY KEY not null, REF_ID INTEGER(18) not null, TABLE_NAME VARCHAR2(30) not null, USER_ID VARCHAR2(40));
CREATE INDEX TB_REF_SELECT_IX1 on TB_REF_SELECT (USER_ID);
CREATE TABLE TB_REGENERATE (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10) not null, SELECT_STATEMENT VARCHAR2(500) not null, TARGET_F_CLASS_ID INTEGER(10) not null);
CREATE TABLE TB_REGENERATE_LABEL (ID INTEGER PRIMARY KEY not null, ACTIVE INTEGER(1), ATTRIBUTE_LIST VARCHAR2(2000), F_CLASS_ID INTEGER(10), LABEL_DEF_ID INTEGER(18), SELECT_STATEMENT VARCHAR2(2000));
CREATE TABLE TB_RELATIONS (ID INTEGER PRIMARY KEY not null, ACTIVE INTEGER(1) default 1 not null, CHILD_COLUMN_NAME VARCHAR2(255), CHILD_TABLE_NAME VARCHAR2(255), CREATE_CHILD INTEGER(1) default 0 not null, DELETE_CHILD VARCHAR2(1) default 'N' not null, PARENT_COLUMN_NAME VARCHAR2(255), PARENT_TABLE_NAME VARCHAR2(255), MERGE_MODE VARCHAR2(1), SPLIT_MODE VARCHAR2(1));
CREATE INDEX IDX_TB_RELATIONS_CC on TB_RELATIONS (CHILD_COLUMN_NAME);
CREATE INDEX IDX_TB_RELATIONS_CT on TB_RELATIONS (CHILD_TABLE_NAME);
CREATE INDEX IDX_TB_RELATIONS_PC on TB_RELATIONS (PARENT_COLUMN_NAME);
CREATE INDEX IDX_TB_RELATIONS_PT on TB_RELATIONS (PARENT_TABLE_NAME);
CREATE TABLE TB_REPORT_CONSTRUC (ID INTEGER PRIMARY KEY not null, A1 REAL(20,8), A2 REAL(20,8), A3 REAL(20,8), A4 REAL(20,8), A5 REAL(20,8), A6 REAL(20,8), ABSZISSE REAL(20,8), CALC_DESCRIPTION VARCHAR2(255), CALC_TYPE INTEGER(10), CREATION_CODE INTEGER(10), CREATION_CODE_P1 VARCHAR2(10), CREATION_CODE_P2 VARCHAR2(10), CREATION_CODE_P3 VARCHAR2(10), CREATION_CODE_P4 VARCHAR2(10), DA0 INTEGER(10), DA1 INTEGER(10), DA2 INTEGER(10), DA3 INTEGER(10), DA4 INTEGER(10), DATE_CREATED DATETIME_as_text, DIRECTION REAL(20,8), DISTANCE REAL(20,8), DISTANCE_MEASURED REAL(20,8), F_CLASS_NAME VARCHAR2(255), F_CLASS_NAME_E1 VARCHAR2(255), F_CLASS_NAME_E2 VARCHAR2(255), F_CLASS_NAME_P1 VARCHAR2(255), F_CLASS_NAME_P2 VARCHAR2(255), F_CLASS_NAME_P3 VARCHAR2(255), F_CLASS_NAME_P4 VARCHAR2(255), FACTOR REAL(20,8), HEADER1 INTEGER(10), JOB_ID INTEGER(18), ORDINATE REAL(20,8), ORIENTATION REAL(20,8), P0 VARCHAR2(255), P1 VARCHAR2(255), P2 VARCHAR2(255), P3 VARCHAR2(255), P4 VARCHAR2(255), R1 REAL(20,8), R2 REAL(20,8), TOLERANCE REAL(20,8), USER_CREATED VARCHAR2(255), VALUE_1 VARCHAR2(255), VALUE_10 VARCHAR2(255), VALUE_2 VARCHAR2(255), VALUE_3 VARCHAR2(255), VALUE_4 VARCHAR2(255), VALUE_5 VARCHAR2(255), VALUE_6 VARCHAR2(255), VALUE_7 VARCHAR2(255), VALUE_8 VARCHAR2(255), VALUE_9 VARCHAR2(255), X0 REAL(20,8), X1 REAL(20,8), X2 REAL(20,8), X3 REAL(20,8), X4 REAL(20,8), Y0 REAL(20,8), Y1 REAL(20,8), Y2 REAL(20,8), Y3 REAL(20,8), Y4 REAL(20,8), Z0 REAL(20,8), Z1 REAL(20,8), Z2 REAL(20,8), Z3 REAL(20,8), Z4 REAL(20,8));
CREATE TABLE TB_REPORT_DEF (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, DMC VARCHAR2(12), FILE_NAME VARCHAR2(255) not null, MODULE_NAME VARCHAR2(255), NAME VARCHAR2(255) not null, PARAMETER VARCHAR2(255), PARENT_REPORT_ID INTEGER(18), constraint TB_REPORT_DEF_CAP_U unique (CAPTION), constraint TB_REPORT_DEF_FILE_U unique (FILE_NAME), constraint TB_REPORT_DEF_NAME_U unique (NAME));
CREATE TABLE TB_RULE_BASE (ID INTEGER PRIMARY KEY not null, ACTIVE INTEGER(1) default 1 not null, AD INTEGER(1) default 0 not null, AI INTEGER(1) default 0 not null, AU INTEGER(1) default 0 not null, BD INTEGER(1) default 0 not null, BI INTEGER(1) default 0 not null, BU INTEGER(1) default 0 not null, F_CLASS_ID INTEGER(10) not null, PARAMETER_1 VARCHAR2(255), PARAMETER_10 VARCHAR2(255), PARAMETER_2 VARCHAR2(255), PARAMETER_3 VARCHAR2(255), PARAMETER_4 VARCHAR2(255), PARAMETER_5 VARCHAR2(255), PARAMETER_6 VARCHAR2(255), PARAMETER_7 VARCHAR2(255), PARAMETER_8 VARCHAR2(255), PARAMETER_9 VARCHAR2(255), PRIORITY INTEGER(10) not null, RULE_DEF_ID INTEGER(18) not null);
CREATE TABLE TB_RULE_DEF (ID INTEGER PRIMARY KEY not null, AD INTEGER(1) default 0 not null, AI INTEGER(1) default 0 not null, ASSEMBLY VARCHAR2(255), AU INTEGER(1) default 0 not null, BD INTEGER(1) default 0 not null, BI INTEGER(1) default 0 not null, BU INTEGER(1) default 0 not null, CLASSNAME VARCHAR2(255), DEFAULT_PRIORITY INTEGER(10) default 100 not null, DESCRIPTION VARCHAR2(4000) not null, EXECUTE_COLUMN VARCHAR2(30), IS_DEFAULT_RULE VARCHAR2(1), IS_ROW INTEGER(1) default 1 not null, IS_SYSTEM INTEGER(1) default 0 not null, NAME VARCHAR2(255) not null, REQUIRES_ID INTEGER(10), RULE_GROUP_ID INTEGER(18), RULE_VERSION VARCHAR2(16), TRIGGER_TEXT VARCHAR2(4000));
CREATE TABLE TB_RULE_FCLASSTYPE (ID INTEGER PRIMARY KEY not null, F_CLASS_TYPE VARCHAR2(1) not null, RULE_DEF_ID INTEGER(18) not null, constraint TB_RULE_FCLASSTYPE_U unique (F_CLASS_TYPE, RULE_DEF_ID));
CREATE TABLE TB_RULE_GROUP (ID INTEGER PRIMARY KEY not null, NAME VARCHAR2(255) not null);
CREATE TABLE TB_RULE_PARAM (ID INTEGER PRIMARY KEY not null, DEFAULT_VALUE VARCHAR2(30), NAME VARCHAR2(255) not null, POSITION INTEGER(2) not null, RULE_DEF_ID INTEGER(18) not null, constraint TB_RULE_PARAM_UK unique (POSITION, RULE_DEF_ID));
CREATE TABLE TB_SCHEMA_PLAN (ID INTEGER PRIMARY KEY not null, LOCATION_DEF_ID INTEGER(18) not null, SCHEMA_TYPE INTEGER(2) not null, TOPOLOGY_ID INTEGER(18) not null);
CREATE TABLE TB_SCHEMA_SETTINGS (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, DESCRIPTION VARCHAR2(1024), KEY VARCHAR2(255) not null, SCHEMA_PLAN_ID INTEGER(18), SCHEMA_TYPE INTEGER(2), UNIT_TYPE_ID INTEGER(18), VALUE VARCHAR2(255), SETTING_TYPE VARCHAR2(1024), constraint TB_SCHEMA_SETTINGS_U unique (KEY, SCHEMA_PLAN_ID, SCHEMA_TYPE));
CREATE TABLE TB_SERVER_ERROR_LOG (NO REAL not null, ERROR_TIME DATETIME_as_text, TEXT VARCHAR2(2000), constraint TB_SERVER_ERROR_LOG_P primary key (NO));
CREATE TABLE TB_SERVER_PROG (ID INTEGER PRIMARY KEY not null, CANCEL INTEGER(1), PERCENT INTEGER(10));
CREATE TABLE TB_SETTINGS (ID INTEGER PRIMARY KEY not null, ITEMKEY VARCHAR2(255), ITEMTHEMA VARCHAR2(255), ITEMVALUE VARCHAR2(2000), MACHINE_ID VARCHAR2(2000), USER_ID VARCHAR2(40));
CREATE INDEX IDX_SETTINGS_MI on TB_SETTINGS (MACHINE_ID);
CREATE INDEX TB_SETTINGS_ITEMKEY_IDX on TB_SETTINGS (ITEMKEY);
CREATE INDEX TB_SETTINGS_ITEMTHEMA_IDX on TB_SETTINGS (ITEMTHEMA);
CREATE INDEX TB_SETTINGS_USERID_IDX on TB_SETTINGS (USER_ID);
CREATE TABLE TB_SETTINGS_COLLECTION (ID INTEGER PRIMARY KEY not null, ITEMVALUE VARCHAR2(2000), PRIORITY INTEGER(5), SETTING_ID INTEGER(18), constraint TB_SETTINGS_COLLECTION_U unique (PRIORITY, SETTING_ID));
CREATE TABLE TB_SPLIT_TOLERANCE (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(255), NAME VARCHAR2(255), VALUE REAL(20,8), constraint TB_SPLIT_TOLERANCE_NAME_U unique (NAME));
CREATE TABLE TB_STATE_INTERSECTION (ID INTEGER PRIMARY KEY not null, INTERSECTION_ID INTEGER(18), JOB_STATE_ID INTEGER(18));
CREATE TABLE TB_SURFACE_CONFIG (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10) not null, NAME VARCHAR2(255), constraint TB_SURFACE_CONFIG_U unique (F_CLASS_ID));
CREATE TABLE TB_SURFACE_DEF (ID INTEGER PRIMARY KEY not null, AZIMUTH REAL(20,8), CAMBER REAL(20,8), DISTANCE REAL(20,8), FID_POINT INTEGER(10), FID_SURFACE INTEGER(10), ISLAND_NR INTEGER(1) default 0 not null, RADIUS REAL(20,8), X REAL(20,8) not null, Y REAL(20,8) not null, Z REAL(20,8));
CREATE TABLE TB_SURFACE_POINT (ID INTEGER PRIMARY KEY not null, POINT_F_CLASS_ID INTEGER(10) not null, PRIORITY INTEGER(2) not null, SURFACE_CONFIG_ID INTEGER(18) not null, constraint TB_SURFACE_POINT_U_POINT_FC unique (POINT_F_CLASS_ID, SURFACE_CONFIG_ID), constraint TB_SURFACE_POINT_U_PRIO unique (PRIORITY, SURFACE_CONFIG_ID));
CREATE TABLE TB_TABLE_MAPPING (ID INTEGER PRIMARY KEY not null, IS_CHANGEABLE INTEGER(1) default 1 not null, MAPPING_TABLE VARCHAR2(255) not null, MODUL_NAME VARCHAR2(255) not null, TB_TABLE VARCHAR2(255) not null);
CREATE TABLE TB_TEMPLATE (ID INTEGER PRIMARY KEY not null, ENABLE_FEATURE_TRACKING INTEGER(1), NAME_NUMBER VARCHAR2(255), USER_FLAG VARCHAR2(255));
CREATE TABLE TB_TEMPLATE_EXPLORER (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10), ID_TEMPLATE INTEGER(18), USER_FLAG VARCHAR2(255));
CREATE INDEX TB_TEMPLATE_EXPLORER_IX1 on TB_TEMPLATE_EXPLORER (ID_TEMPLATE);
CREATE INDEX TB_TEMPLATE_EXPLORER_IX2 on TB_TEMPLATE_EXPLORER (F_CLASS_ID);
CREATE TABLE TB_TEMPLATE_FEATURE (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10), GEOM FDO_GEOMETRY_as_blob, ID_REFERENCE_RECORD INTEGER(18), ID_TEMPLATE INTEGER(18), INSTANTIATE INTEGER(1), ORIENTATION REAL(6,3) default 90 not null, USER_FLAG VARCHAR2(255));
CREATE INDEX TB_TEMPLATE_FEATURE_IX1 on TB_TEMPLATE_FEATURE (ID_TEMPLATE);
CREATE TABLE TB_TEMPLATE_RELATION (ID INTEGER PRIMARY KEY not null, ID_RELATIONS INTEGER(18), ID_TEMPLATE_FEATURE_CHILD INTEGER(18), ID_TEMPLATE_FEATURE_PARENT INTEGER(18), USER_FLAG VARCHAR2(255));
CREATE INDEX TB_TEMPLATE_RELATION_IX1 on TB_TEMPLATE_RELATION (ID_TEMPLATE_FEATURE_CHILD);
CREATE INDEX TB_TEMPLATE_RELATION_IX2 on TB_TEMPLATE_RELATION (ID_TEMPLATE_FEATURE_PARENT);
CREATE TABLE TB_TMP_PERIMETER (ID INTEGER PRIMARY KEY not null, GEOM FDO_GEOMETRY_as_blob, INTERSECTION_ID INTEGER(18), JOB_ID INTEGER(18));
CREATE TABLE TB_TOPOLOGY_DEF (ID INTEGER PRIMARY KEY not null, ADD_SQL_STATEMENT VARCHAR2(2000), DEF_TYPE CHAR(1) not null, F_CLASS_ID INTEGER(10), FLOW_ATTR_NAME VARCHAR2(30), FLOW_VALUES_BACKWARD VARCHAR2(1000), FLOW_VALUES_BOTH VARCHAR2(1000), FLOW_VALUES_FORWARD VARCHAR2(1000), SPLIT_ATTR_NAME VARCHAR2(30), TOPOLOGY_ID INTEGER(18));
CREATE TABLE TB_TOPOLOGY_FC_SPLIT (ID INTEGER PRIMARY KEY not null, ATTR_VALUE VARCHAR2(255), CAPTION VARCHAR2(255) not null, TOPOLOGY_DEF_ID INTEGER(18) not null);
CREATE TABLE TB_TOPOLOGY_MATRIX (ID INTEGER PRIMARY KEY not null, FROM_F_CLASS_ID INTEGER(10), TO_F_CLASS_ID INTEGER(10), TOPOLOGY_ID INTEGER(18));
CREATE TABLE TB_UFID (FID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10), LOCKED INTEGER(10), TOUCH_TS TIMESTAMP_as_text(6));
CREATE INDEX TB_UFID_TS on TB_UFID (F_CLASS_ID, TOUCH_TS);
CREATE TABLE TB_UTIL (ID INTEGER PRIMARY KEY not null, F_CLASS_ID_LINE INTEGER(10), F_CLASS_ID_POINT INTEGER(10), MAIN_UTIL_ID INTEGER(18), NAME VARCHAR2(255) not null, TOPOLOGY_ID INTEGER(18), constraint TB_UTIL_NAME_U unique (NAME));
CREATE TABLE TB_UTIL_DICTIONARY (ID INTEGER PRIMARY KEY not null, F_CLASS_ID_ATTR INTEGER(10) not null, GEOMETRY_TYPE VARCHAR2(1), MAX_CONNECTED INTEGER(10), UTIL_ID INTEGER(18), constraint TB_UTIL_DICTIONARY_NAMEU unique (F_CLASS_ID_ATTR));
CREATE TABLE TB_VAL_RESULTS (ID INTEGER PRIMARY KEY not null, F_CLASS_NAME VARCHAR2(30), FID INTEGER(10), JOB_ID INTEGER(18), JOB_VERSION INTEGER(10), RESULT VARCHAR2(1000));
CREATE TABLE TB_VARIABLE (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(4000), KEY VARCHAR2(255) not null, USER_ID VARCHAR2(36), VALUE VARCHAR2(4000), constraint TB_VARIABLE_U unique (KEY, USER_ID));
CREATE TABLE TB_VIEW_DEFINITION (ID VARCHAR2(36) not null, PRIMARY_KEY_COLUMN VARCHAR2(255) not null, VIEW_NAME VARCHAR2(255) not null, constraint TB_VIEW_DEFINITION_P primary key (ID));
CREATE TABLE TB_GN_LIST_CONFIG (ID VARCHAR2(40) not null, ITEM_CHECKED INTEGER(1), ITEM_INDEX INTEGER(5), ITEM_VALUE VARCHAR2(255), LIST_ID VARCHAR2(255), USER_ID VARCHAR2(40), constraint TB_GN_LIST_CONFIG_P primary key (ID));
CREATE INDEX IDX_GN_LIST_CONFIG_LI on TB_GN_LIST_CONFIG (LIST_ID);
CREATE INDEX IDX_GN_LIST_CONFIG_UI on TB_GN_LIST_CONFIG (USER_ID);
CREATE TABLE TB_GN_MENU_ITEM (ID VARCHAR2(40) not null, CAPTION VARCHAR2(255), NAME VARCHAR2(255), PARENT VARCHAR2(255), constraint TB_GN_MENU_ITEM_P primary key (ID));
CREATE TABLE TB_RPT_SQL (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(4000), NAME VARCHAR2(255), REPORT_ID INTEGER(18), SQL VARCHAR2(4000), SQL_ID VARCHAR2(40));
CREATE INDEX IDX_RPT_SQL_RI on TB_RPT_SQL (REPORT_ID);
CREATE TABLE TB_RPT_SECTION (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(4000), GLUE INTEGER(1), GROUP_ID INTEGER(18), HEIGHT INTEGER(10), NAME VARCHAR2(255), ORDER_INDEX INTEGER(10), SECTION_TYPE INTEGER(2));
CREATE INDEX IDX_RPT_SECTION_GI on TB_RPT_SECTION (GROUP_ID);
CREATE TABLE TB_RPT_SQL_CODE (ID INTEGER PRIMARY KEY not null, ORDER_INDEX INTEGER(5), REPORT_ID INTEGER(18), SQL VARCHAR2(4000), SQL_ID VARCHAR2(40));
CREATE INDEX IDX_RPT_SQLCODE_RI on TB_RPT_SQL_CODE (REPORT_ID);
CREATE INDEX IDX_RPT_SQLCODE_SI on TB_RPT_SQL_CODE (SQL_ID);
CREATE TABLE TB_GN_USERGROUP_DIALOG (ID INTEGER PRIMARY KEY not null, DIALOG_ID INTEGER(18), USERGROUP_ID VARCHAR2(40), constraint IDX_GN_USERGDIA_IDTN unique (DIALOG_ID, USERGROUP_ID));
CREATE TABLE TB_RPT_PAGE (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(4000), FRAME_HEIGHT INTEGER(10), FRAME_LEFT INTEGER(10), FRAME_TOP INTEGER(10), FRAME_VISIBLE INTEGER(1), FRAME_WIDTH INTEGER(10), HEIGHT INTEGER(10), LEFT INTEGER(10), NAME VARCHAR2(255), ORDER_INDEX INTEGER(10), REPORT_ID INTEGER(10), TOP INTEGER(10), WIDTH INTEGER(10));
CREATE INDEX IDX_RPT_PAGE_RI on TB_RPT_PAGE (REPORT_ID);
CREATE TABLE TB_GN_DIALOG_HIGHLIGHT (ID INTEGER PRIMARY KEY not null, DIALOG_ID INTEGER(18), HIGHLIGHT_FEATURECLASS VARCHAR2(255), HIGHLIGHT_FILTER VARCHAR2(255));
CREATE INDEX IDX_GN_DIALOG_HIGHLIGHT_DID on TB_GN_DIALOG_HIGHLIGHT (DIALOG_ID);
CREATE TABLE TB_GN_DIALOG_BAR_ITEM (ID VARCHAR2(40) not null, CAPTION VARCHAR2(255), NAME VARCHAR2(255), PARENT_NAME VARCHAR2(255), PICTUREFILE VARCHAR2(255), constraint TB_GN_DIALOG_BAR_ITEM_P primary key (ID));
CREATE TABLE TB_RPT_CHART (ID INTEGER PRIMARY KEY not null, CONTROL_ID INTEGER(18), ORDER_INDEX INTEGER(10), TEMPLATE_DATA VARCHAR2(4000));
CREATE INDEX IDX_RPT_CHART_CI on TB_RPT_CHART (CONTROL_ID);
CREATE INDEX IDX_RPT_CHART_OI on TB_RPT_CHART (ORDER_INDEX);
CREATE TABLE TB_RPT_CONTROL (ID INTEGER PRIMARY KEY not null, BACK_COLOR VARCHAR2(50), CONTENT VARCHAR2(4000), CONTENT_TYPE INTEGER(3), DYNAMICMULTILINE INTEGER(1), FONT_BOLD INTEGER(1), FONT_ITALIC INTEGER(1), FONT_NAME VARCHAR2(255), FONT_NAME_PDF VARCHAR2(255), FONT_SIZE INTEGER(3), FONT_STRIKEOUT INTEGER(1), FONT_UNDERLINED INTEGER(1), FORE_COLOR VARCHAR2(50), FORMAT VARCHAR2(255), HEIGHT INTEGER(10), HORIZONTALALIGN INTEGER(2), LEFT INTEGER(10), LOCKED INTEGER(1), PRIORITY INTEGER(10), STYLE INTEGER(5), SUPPRESS VARCHAR2(255), SUPPRESSDUPLICATES INTEGER(1), TOP INTEGER(10), TRANSLATE INTEGER(1), VERTICALALIGN INTEGER(2), VERTICALAUTOHEIGHT INTEGER(10), WIDTH INTEGER(10), WIDTHASCII INTEGER(10), ZONE_ID INTEGER(18), WORDWRAP INTEGER(1));
CREATE INDEX IDX_RPT_CONTROL_ZI on TB_RPT_CONTROL (ZONE_ID);
CREATE TABLE TB_GN_DIALOG_PROJECTION (ID INTEGER PRIMARY KEY not null, DIALOG_ID INTEGER(18), PROJECTION_DIALOG_NAME VARCHAR2(255), PROJECTION_FILTER VARCHAR2(255), PROJECTION_NAME VARCHAR2(255));
CREATE INDEX IDX_GN_DIALOG_PROJECTION_DID on TB_GN_DIALOG_PROJECTION (DIALOG_ID);
CREATE TABLE TB_GN_DOCUMENT_KEY (ID INTEGER PRIMARY KEY not null, DESCRIPTION VARCHAR2(255), KEY VARCHAR2(255));
CREATE TABLE TB_GN_DIALOG_BAR (ID INTEGER PRIMARY KEY not null, NAME VARCHAR2(255));
CREATE TABLE TB_RPT_ZONE (ID INTEGER PRIMARY KEY not null, AUTOSIZE INTEGER(1), COMMENTARY VARCHAR2(4000), HEIGHT INTEGER(10), NAME VARCHAR2(255), ORDER_INDEX INTEGER(10), PAGEBREAKAFTER INTEGER(1), PAGEBREAKBEFORE INTEGER(1), SECTION_ID INTEGER(18), SUPPRESS VARCHAR2(255));
CREATE INDEX IDX_RPT_ZONE_SI on TB_RPT_ZONE (SECTION_ID);
CREATE TABLE TB_GN_DOCUMENT_BAR (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255), NAME VARCHAR2(255));
CREATE TABLE TB_GN_INFO_REDIRECT (ID INTEGER PRIMARY KEY not null, DIALOG_COLUMN_NAME VARCHAR2(255), DIALOG_DOCUMENT_NAME VARCHAR2(255), DIALOG_TABLE_NAME VARCHAR2(255), F_COLUMN_NAME VARCHAR2(255), F_TABLE_NAME VARCHAR2(255), INFO_FILTER VARCHAR2(2000));
CREATE INDEX IDX_GN_INFO_REDIRECT_FN on TB_GN_INFO_REDIRECT (F_TABLE_NAME);
CREATE TABLE TB_RPT_PLUGIN (ID INTEGER PRIMARY KEY not null, ASSEMBLYNAME VARCHAR2(255), CLASSNAME VARCHAR2(255), COMMENTARY VARCHAR2(4000), FUNCTIONNAME VARCHAR2(255), NAME VARCHAR2(255), NAMESPACE VARCHAR2(255), REPORT_ID INTEGER(18));
CREATE INDEX IDX_RPT_PLUGIN_RI on TB_RPT_PLUGIN (REPORT_ID);
CREATE TABLE TB_GN_MENU_NODE_FILTER (ID VARCHAR2(40) not null, MENU_ITEM_NAME VARCHAR2(2000), NODE_NAME VARCHAR2(2000), USERGROUP_ID VARCHAR2(40), constraint TB_GN_MENU_NODE_FILTER_P primary key (ID));
CREATE INDEX IDX_GN_MENU_NODE_FILTER_MIN on TB_GN_MENU_NODE_FILTER (MENU_ITEM_NAME);
CREATE INDEX IDX_GN_MENU_NODE_FILTER_NON on TB_GN_MENU_NODE_FILTER (NODE_NAME);
CREATE INDEX IDX_GN_MENU_NODE_FILTER_UGI on TB_GN_MENU_NODE_FILTER (USERGROUP_ID);
CREATE TABLE TB_GN_DIALOG_DETAIL (ID INTEGER PRIMARY KEY not null, DETAIL_DIALOG_NAME VARCHAR2(255), MASTER_DIALOG_ID INTEGER(18), TABORDER INTEGER(10), VISIBLE INTEGER(1));
CREATE INDEX IDX_GN_DIALOG_DETAIL_PID on TB_GN_DIALOG_DETAIL (MASTER_DIALOG_ID);
CREATE TABLE TB_GN_FLYIN_USER (ID INTEGER PRIMARY KEY not null, ALWAYSONTOP INTEGER(1), DOCKSTATE INTEGER(2), FLY_HEIGHT INTEGER(10), NAME VARCHAR2(255), ORDER_INDEX INTEGER(5), PARENT_FLYIN VARCHAR2(255), USER_ID VARCHAR2(40), WIN_HEIGHT INTEGER(10), WIN_LEFT INTEGER(10), WIN_TOP INTEGER(10), WIN_WIDTH INTEGER(10));
CREATE INDEX IDX_GN_FLYIN_USER_NA on TB_GN_FLYIN_USER (NAME);
CREATE INDEX IDX_GN_FLYIN_USER_UI on TB_GN_FLYIN_USER (USER_ID);
CREATE TABLE TB_GN_DIALOG (ID INTEGER PRIMARY KEY not null, AUTOGRIDORDER INTEGER(1) default 1, AUTOTABORDER INTEGER(1), CAPTION VARCHAR2(255), CAPTION_LID VARCHAR2(36), DEFAULTHEIGHT INTEGER(10), DEFAULTISDOCKED INTEGER(1), DEFAULTLEFT INTEGER(10), DEFAULTMODE INTEGER(2), DEFAULTORDERBY VARCHAR2(4000), DEFAULTTAB INTEGER(10) default 1, DEFAULTTABSVISIBLE INTEGER(1) default 1, DEFAULTTOP INTEGER(10), DEFAULTWIDTH INTEGER(10), DETAIL_FIELDNAME VARCHAR2(50), DETAILHEIGHT INTEGER(10), DIALOGLAYOUTNAME VARCHAR2(255), DIALOGNAME VARCHAR2(255), HELPCONTEXT VARCHAR2(255), HELPFILENAME VARCHAR2(255), HELPURL VARCHAR2(255), KEYCOLUMNNAME VARCHAR2(255), LANGUAGE_GROUP VARCHAR2(36), MASTER_FIELDNAME VARCHAR2(50), REGISTERNAMES VARCHAR2(2000), STARTMODE INTEGER(2), TABGROUPSUSPEND VARCHAR2(2000), TABLENAME VARCHAR2(255), TOOLBAR_ID INTEGER(18), constraint IDX_GN_DIALOG_DITY unique (DIALOGLAYOUTNAME, DIALOGNAME));
CREATE INDEX IDX_GN_DIALOG_TN on TB_GN_DIALOG (TABLENAME);
CREATE TABLE TB_GN_DIALOG_USER (ID INTEGER PRIMARY KEY not null, ACTIVEREFRECORD VARCHAR2(255), ACTIVETAB INTEGER(2), COLWIDTHS VARCHAR2(2000), DEFAULTMODE INTEGER(2), DETAILHEIGHT INTEGER(20), DIALOG_ID INTEGER(18), ISDOCKED INTEGER(1), STARTMODE INTEGER(2), TABSVISIBLE INTEGER(1), USER_ID VARCHAR2(40));
CREATE INDEX IDX_GN_DIALOG_USER_DI on TB_GN_DIALOG_USER (DIALOG_ID);
CREATE INDEX IDX_GN_DIALOG_USER_UI on TB_GN_DIALOG_USER (USER_ID);
CREATE TABLE TB_GN_SELECTION (ID VARCHAR2(40) not null, CASE_ID VARCHAR2(40), CHARVALUE VARCHAR2(255), KEYVALUE INTEGER(20), USER_ID VARCHAR2(255), constraint TB_GN_SELECTION_P primary key (ID));
CREATE INDEX IDX_GN_SELECTION_CID on TB_GN_SELECTION (CASE_ID);
CREATE INDEX IDX_GN_SELECTION_UID on TB_GN_SELECTION (USER_ID);
CREATE TABLE TB_GN_REPORT_FILTER (ID INTEGER PRIMARY KEY not null, DIALOG_ID INTEGER(18), NAME VARCHAR2(255), USERGROUP_ID VARCHAR2(40));
CREATE INDEX IDX_GN_REPORT_FILTER_DID on TB_GN_REPORT_FILTER (DIALOG_ID);
CREATE TABLE TB_RPT_GROUP (ID INTEGER PRIMARY KEY not null, AFTERQUERY VARCHAR2(100), BEFOREQUERY VARCHAR2(100), COMMENTARY VARCHAR2(4000), DATASOURCE INTEGER(2), GLUE INTEGER(1), NAME VARCHAR2(255), ORDER_INDEX INTEGER(10), PAGE_ID INTEGER(18), PARALLEL INTEGER(1), PARENT_ID INTEGER(18), REPEATHEADONNEWPAGE INTEGER(1), RESETPAGECOUNTER INTEGER(1), SHOWFOOT INTEGER(1) default 1, SHOWHEAD INTEGER(1) default 1, SQL VARCHAR2(4000), SQL_ID VARCHAR2(40), SUPPRESSIFNORECORDS INTEGER(1) default 1);
CREATE INDEX IDX_RPT_GROUP_PI on TB_RPT_GROUP (PAGE_ID);
CREATE INDEX IDX_RPT_GROUP_PRI on TB_RPT_GROUP (PARENT_ID);
CREATE TABLE TB_GN_FLYIN_FILTER (ID VARCHAR2(40) not null, FLYIN_ID INTEGER(18) not null, NAME VARCHAR2(255), USERGROUP_ID VARCHAR2(40), constraint TB_GN_FLYIN_FILTER_P primary key (ID));
CREATE INDEX IDX_GN_FLYIN_FILTER_BI on TB_GN_FLYIN_FILTER (FLYIN_ID);
CREATE INDEX IDX_GN_FLYIN_FILTER_GI on TB_GN_FLYIN_FILTER (USERGROUP_ID);
CREATE TABLE TB_GN_MENU_FILTER (ID VARCHAR2(40) not null, NAME VARCHAR2(255), USERGROUP_ID VARCHAR2(40), constraint TB_GN_MENU_FILTER_P primary key (ID));
CREATE INDEX IDX_GN_MENU_FILTER_UGI on TB_GN_MENU_FILTER (USERGROUP_ID);
CREATE TABLE TB_GN_DIALOG_SCRIPTCODE (ID VARCHAR2(40) not null, DIALOG_ID INTEGER(18), ORDER_INDEX INTEGER(5), SCRIPT_ID VARCHAR2(40), SCRIPTCODE VARCHAR2(4000), constraint TB_GN_DIALOG_SCRIPTCODE_P primary key (ID));
CREATE TABLE TB_RPT_FUNCTION_CODE (ID INTEGER PRIMARY KEY not null, CODE VARCHAR2(4000), FUNCTION_NAME VARCHAR2(255), ORDER_INDEX INTEGER(5), REPORT_ID INTEGER(18));
CREATE INDEX IDX_RPT_FUNCODE_FN on TB_RPT_FUNCTION_CODE (FUNCTION_NAME);
CREATE INDEX IDX_RPT_FUNCODE_RI on TB_RPT_FUNCTION_CODE (REPORT_ID);
CREATE TABLE TB_GN_FLYIN (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255), NAME VARCHAR2(255));
CREATE TABLE TB_RPT_PARAMETER (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(4000), CONTENT VARCHAR2(4000), NAME VARCHAR2(255), REPORT_ID INTEGER(18));
CREATE INDEX IDX_RPT_PARAMETER_RI on TB_RPT_PARAMETER (REPORT_ID);
CREATE TABLE TB_CRYSTAL_REPORTS (ID VARCHAR2(100) not null, CHARVALUE VARCHAR2(2000), FID INTEGER(10), USER_ID VARCHAR2(40), constraint TB_CRYSTAL_REPORTS_P primary key (ID));
CREATE INDEX IDX_GN_CRYREP_UID on TB_CRYSTAL_REPORTS (USER_ID);
CREATE TABLE TB_FORM_LOCATION (ID INTEGER PRIMARY KEY not null, CLIENT_IDENTITY VARCHAR2(255), HEIGHT INTEGER(10), LEFT INTEGER(10), NAME VARCHAR2(255), TOP INTEGER(10), USER_ID VARCHAR2(40), WIDTH INTEGER(10));
CREATE INDEX IDX_GN_FORM_LOC_USER_IT on TB_FORM_LOCATION (CLIENT_IDENTITY);
CREATE INDEX IDX_GN_FORM_LOC_USER_NM on TB_FORM_LOCATION (NAME);
CREATE INDEX IDX_GN_FORM_LOC_USER_UI on TB_FORM_LOCATION (USER_ID);
CREATE TABLE TB_RPT_FUNCTION (ID INTEGER PRIMARY KEY not null, CODE VARCHAR2(4000), COMMENTARY VARCHAR2(4000), LARGECODE INTEGER(1), NAME VARCHAR2(255), REPORT_ID INTEGER(18));
CREATE INDEX IDX_RPT_FUNCTION_RI on TB_RPT_FUNCTION (REPORT_ID);
CREATE TABLE TB_FEATURE_DOCUMENT (ID INTEGER PRIMARY KEY not null, AUTHOR VARCHAR2(255), COMMENTARY VARCHAR2(1000), CREATIONDATE DATETIME_as_text, FID_PARENT INTEGER(10), FILENAME VARCHAR2(1000), TITLE VARCHAR2(255));
CREATE INDEX IDX_FEATURE_DOC_FI on TB_FEATURE_DOCUMENT (FID_PARENT);
CREATE TABLE TB_GN_DIALOG_MACHINE_USER (ID INTEGER PRIMARY KEY not null, CLIENT_IDENTITY VARCHAR2(255), DIALOG_ID INTEGER(18), HEIGHT INTEGER(10), LEFT INTEGER(10), TOP INTEGER(10), USER_ID VARCHAR2(40), WIDTH INTEGER(10));
CREATE INDEX IDX_GN_DIALOG_MACH_USER_DI on TB_GN_DIALOG_MACHINE_USER (DIALOG_ID);
CREATE INDEX IDX_GN_DIALOG_MACH_USER_IT on TB_GN_DIALOG_MACHINE_USER (CLIENT_IDENTITY);
CREATE INDEX IDX_GN_DIALOG_MACH_USER_UI on TB_GN_DIALOG_MACHINE_USER (USER_ID);
CREATE TABLE TB_GN_REPORT (ID INTEGER PRIMARY KEY not null, DESKTOP INTEGER(1) default 1, DIALOG_ID INTEGER(18), FILENAME VARCHAR2(255), NAME VARCHAR2(255), PROPS VARCHAR2(1000), REPORTTYPE VARCHAR2(255), USERGROUPS VARCHAR2(2000), WEB INTEGER(1) default 1);
CREATE INDEX IDX_GN_REPORT_DID on TB_GN_REPORT (DIALOG_ID);
CREATE TABLE TB_GN_DIRECTORY_ALIAS (ID INTEGER PRIMARY KEY not null, ALIASNAME VARCHAR2(255), DIRECTORYNAME VARCHAR2(255));
CREATE TABLE TB_GN_DIALOG_FILTER (ID INTEGER PRIMARY KEY not null, DIALOG_ID INTEGER(18), FILTER VARCHAR2(2000), ISPUBLIC INTEGER(1), NAME VARCHAR2(255), USER_ID VARCHAR2(40));
CREATE INDEX IDX_GN_DIALOG_FILTER_DID on TB_GN_DIALOG_FILTER (DIALOG_ID);
CREATE TABLE TB_GN_DOCUMENT_BAR_ITEM (ID VARCHAR2(40) not null, BAR_ID INTEGER(18), CAPTION VARCHAR2(255), NAME VARCHAR2(255), PARENT_NAME VARCHAR2(255), PICTUREFILE VARCHAR2(255), constraint TB_GN_DOCUMENT_BAR_ITEM_P primary key (ID));
CREATE INDEX IDX_GN_DOCUMENT_BAR_ITEM_BI on TB_GN_DOCUMENT_BAR_ITEM (BAR_ID);
CREATE TABLE TB_RPT_CHART_CODE (ID INTEGER PRIMARY KEY not null, CODE VARCHAR2(4000), CONTROL_ID INTEGER(18), ORDER_INDEX INTEGER(5));
CREATE INDEX IDX_RPT_CHART_CODE_CI on TB_RPT_CHART_CODE (CONTROL_ID);
CREATE TABLE TB_GN_DIALOG_BAR_FILTER (ID VARCHAR2(40) not null, BAR_ID INTEGER(18) not null, NAME VARCHAR2(255), USERGROUP_ID VARCHAR2(40), constraint TB_GN_DIALOG_BAR_FILTER_P primary key (ID));
CREATE INDEX IDX_GN_DIALOG_BAR_FILTER_BI on TB_GN_DIALOG_BAR_FILTER (BAR_ID);
CREATE INDEX IDX_GN_DIALOG_BAR_FILTER_GI on TB_GN_DIALOG_BAR_FILTER (USERGROUP_ID);
CREATE TABLE TB_GN_CONTROL (ID INTEGER PRIMARY KEY not null, ALIGNRIGHT INTEGER(1), ALLOWDOUBLECLICK INTEGER(1), ALLOWMULTIROWUPDATE INTEGER(1), ALLOWREFERENCE INTEGER(1) default 1, ASSEMBLYNAME VARCHAR2(255), BASEVISIBILITY INTEGER(1), CAPTION VARCHAR2(255), CLASSNAME VARCHAR2(255), CLASSNAMESPACE VARCHAR2(255), COLUMNNAME VARCHAR2(50), COLWIDTH INTEGER(20), CUSTOMPROPS VARCHAR2(1000), DATEFORMAT VARCHAR2(50), DEFAULTVALUE VARCHAR2(255), DETAILCONTROL VARCHAR2(100), DETAILDOCUMENT VARCHAR2(100), DETAILFIELDISNUMERIC INTEGER(1) default 1, DETAILFIELDNAME VARCHAR2(255), DETAILFILTER VARCHAR2(255), DETAILLIST VARCHAR2(255), DETAILORDERBY VARCHAR2(255), DETAILTABLE VARCHAR2(4000), DIALOG_ID INTEGER(18), ENFORCEUPPER INTEGER(1), FALSEVALUE VARCHAR2(100), FIDBUTTON INTEGER(1), FILENAME VARCHAR2(2000), FILESELECTION INTEGER(1), FILTER VARCHAR2(2000), FILTERCOMBOBOX INTEGER(1), FONTNAME VARCHAR2(100), FONTSIZE INTEGER(10), FONTSTYLE VARCHAR2(10), FORECOLOR VARCHAR2(100), FORMULA VARCHAR2(4000), GRIDORDER INTEGER(5), GROUPLOCKED VARCHAR2(2000), GROUPSUSPEND VARCHAR2(2000), HEIGHT INTEGER(20), HELPCONTEXT VARCHAR2(255), HELPFILENAME VARCHAR2(255), HELPURL VARCHAR2(255), HIDEATGRID INTEGER(1), HIGHLIGHTBUTTON INTEGER(1), IGNORENULL INTEGER(1), ISLOCKED INTEGER(1), ISOBLIGATE INTEGER(1), ISUNIQUE INTEGER(1), ITEMHEIGHT INTEGER(10), ITEMWIDTH INTEGER(10), LEFT INTEGER(20), LINESIZE INTEGER(2), MASTERFIELDNAME VARCHAR2(40), MASTERFILTER VARCHAR2(2000), MASTERLIST VARCHAR2(255), MASTERORDERBY VARCHAR2(255), MASTERTABLE VARCHAR2(100), MULTILINE INTEGER(1), NAME VARCHAR2(255), NEXTCONTROL VARCHAR2(255), NULLVALUE VARCHAR2(100), PLUGINASSEMBLYNAME VARCHAR2(100), PLUGINBASECLASSNAME VARCHAR2(100), PLUGINCLASSNAME VARCHAR2(100), PLUGINCLASSNAMESPACE VARCHAR2(100), PLUGINCONTROLNAME VARCHAR2(100), PLUGINNAME VARCHAR2(100), PRECISION VARCHAR2(10), PRECISIONXY INTEGER(2), PRECISIONZ INTEGER(2), PRIORITY INTEGER(10), PROJECTIONBUTTON INTEGER(1), REFERENCEBUTTON INTEGER(1), SCRIPT_ID VARCHAR2(40), SHOWENDPOINTONLY INTEGER(1), SHOWINTERPRETATION INTEGER(1), SHOWSTARTPOINTONLY INTEGER(1), SHOWX INTEGER(1), SHOWY INTEGER(1), SHOWZ INTEGER(1), SQL VARCHAR2(2000), STRETCHIMAGE INTEGER(1), TABID INTEGER(2), TEXT VARCHAR2(2000), TOOLTIPTEXT VARCHAR2(255), TOP INTEGER(20), TRUEVALUE VARCHAR2(100), USEBUFFER INTEGER(1), VALIDATIONCODE VARCHAR2(4000), VALIDATIONMESSAGE VARCHAR2(2000), VERTICAL INTEGER(1), WIDTH INTEGER(20), WORDWRAP INTEGER(1), constraint IDX_GN_CONTROL_NADI unique (DIALOG_ID, NAME));
CREATE INDEX IDX_GN_CONTROL_DI on TB_GN_CONTROL (DIALOG_ID);
CREATE TABLE TB_GN_DOCUMENT_BAR_FILTER (ID VARCHAR2(40) not null, BAR_ID INTEGER(18) not null, NAME VARCHAR2(255), USERGROUP_ID VARCHAR2(40), constraint TB_GN_DOCUMENT_BAR_FILTER_P primary key (ID));
CREATE INDEX IDX_GN_DOCUMENT_BAR_FILTER_BI on TB_GN_DOCUMENT_BAR_FILTER (BAR_ID);
CREATE INDEX IDX_GN_DOCUMENT_BAR_FILTER_GI on TB_GN_DOCUMENT_BAR_FILTER (USERGROUP_ID);
CREATE TABLE TB_TOPOLOGY (ID INTEGER PRIMARY KEY not null, ARC_LINEARIZE REAL(20,8), CAPTION VARCHAR2(255) not null, DEFAULT_FLOW INTEGER(1), INITIALIZED INTEGER(1), NAME VARCHAR2(255) not null, POINT_SNAP REAL(20,8), POLY_LINEARIZE REAL(20,8), SPATIAL_TOLERANCE REAL(20,8), TYPE VARCHAR2(1), AREA_MODIFICATION_TOLERANCE REAL(20,8), constraint sqlite_autoindex_TB_TOPOLOGY_1 unique (NAME));
CREATE TABLE TB_INTERSECTION (ID INTEGER PRIMARY KEY not null, ADJUST_EXCLUDE VARCHAR2(4000), ADJUST_SECOND INTEGER(1) default 0 not null, BUFFER_PRIM_FC REAL(20,8) default 0.001 not null, F_CLASS_NAME_INTER VARCHAR2(20) not null, F_CLASS_NAME_PRIM VARCHAR2(30) not null, F_CLASS_NAME_SEC VARCHAR2(30) not null, NAME VARCHAR2(255) not null, PRIM_JOBID INTEGER(18) default 1 not null, PRIM_UPDATE_STATEMENT VARCHAR2(4000), SEC_JOBID INTEGER(18) default 1 not null, SEC_UPDATE_STATEMENT VARCHAR2(4000), STORE_GEOMETRY INTEGER(1) default 0 not null, TOL_AREA_NOMINAL REAL(20,8) default 0.5 not null, TOLERANCE REAL(20,8) not null, TYPE VARCHAR2(2) not null, WHERE_CLAUSE_PRIM VARCHAR2(500), WHERE_CLAUSE_SEC VARCHAR2(500), CAPTION VARCHAR2(255) not null, constraint sqlite_autoindex_TB_INTERSECTION_1 unique (NAME));
CREATE TABLE TB_FUNCTIONALITEM (ID VARCHAR2(36) not null, CMDGLOBALNAME VARCHAR2(255) not null, CMDLOCALNAME VARCHAR2(255) not null, constraint TB_FUNCTIONALITEM_P primary key (ID));
CREATE TABLE TB_FCONT (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, IMAGE VARCHAR2(255), NAME VARCHAR2(255) not null, TARGET_KEY VARCHAR2(255) not null, constraint TB_FCONT_NAME_U unique (NAME));
CREATE TABLE TB_TOPIC (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, NAME VARCHAR2(255) not null, TOPIC_ID INTEGER(18), constraint sqlite_autoindex_TB_TOPIC_1 unique (CAPTION), constraint sqlite_autoindex_TB_TOPIC_2 unique (NAME));
CREATE TABLE TB_WORKFLOW (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, IS_SYSTEM INTEGER(1) default 0 not null, NAME VARCHAR2(255) not null, PARENT_ID INTEGER(18), PICTURE VARCHAR2(255), PRIORITY INTEGER(10), SCRIPTCODE VARCHAR2(4000), TARGET VARCHAR2(1) default 'C' not null, constraint sqlite_autoindex_TB_WORKFLOW_1 unique (CAPTION), constraint sqlite_autoindex_TB_WORKFLOW_2 unique (NAME));
CREATE TABLE TB_EXPLORER_GROUP_VIEW (ID VARCHAR2(36) not null, EXPLORER_GROUP_ID INTEGER(18) not null, SELECTED INTEGER(1) default 0 not null, USER_ID VARCHAR2(36), primary key (ID));
CREATE TABLE TB_JOB_SWITCH (IP VARCHAR2(255) not null, JOB_ID INTEGER(18) not null, LEASE TIMESTAMP_as_text(6) not null, constraint TB_JOB_SWITCH_P primary key (IP));
CREATE TABLE TB_VIEWPORT (ID VARCHAR2(36) not null, GEOM FDO_GEOMETRY_as_blob not null, NAME VARCHAR2(255) not null, POSITION_FINDER_ID INTEGER(10), POSITION_FINDER_KEY_1 VARCHAR2(255), POSITION_FINDER_KEY_2 VARCHAR2(255), POSITION_FINDER_KEY_3 VARCHAR2(255), POSITION_FINDER_KEY_4 VARCHAR2(255), USER_ID VARCHAR2(36), primary key (ID));
CREATE TABLE TB_VIEWPORT_VIEW (ID VARCHAR2(36) not null, SELECTED INTEGER(1) default 0 not null, USER_ID VARCHAR2(36), VIEWPORT_ID VARCHAR2(36) not null, primary key (ID));
CREATE TABLE TB_TMP_INTERSECTED (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10) not null, FID INTEGER(10) not null, JOB_ID INTEGER(10) not null);
CREATE TABLE TB_LRS (ID INTEGER PRIMARY KEY not null, CAPTION VARCHAR2(255) not null, NAME VARCHAR2(255) not null, OFFSET_SYSTEM INTEGER(2) not null, PREFIX VARCHAR2(7) not null, constraint TB_LRS_CAPTION_U unique (CAPTION), constraint TB_LRS_PREFIX_U unique (PREFIX));
CREATE TABLE TB_RPT_REPORT (ID INTEGER PRIMARY KEY not null, COMMENTARY VARCHAR2(4000), HEIGHT INTEGER(10) default 2800, HTMLTITLE VARCHAR2(255), ISPRIVATE INTEGER(1), LANDSCAPE INTEGER(1), MODULNAME VARCHAR2(255), NAME VARCHAR2(255), PAPERKIND INTEGER(5), WIDTH INTEGER(10) default 2100, CAPTION VARCHAR2(255) not null);
CREATE TABLE TB_LRS_FC (ID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(18) not null, ID_LRS INTEGER(18) not null, LOCK_GEOMETRY INTEGER(1) default 0 not null, LRS_BEHAVIOR INTEGER(2) default 1 not null, LRS_ROLE INTEGER(2) not null, ORIENTATION_BEHAVIOR INTEGER(2) default 2 not null);
CREATE TABLE TB_UNIT (ID INTEGER PRIMARY KEY not null, BASE_OFFSET REAL, CAPTION NVARCHAR2(255), ID_UNIT_TYPE INTEGER(18) not null, NAME NVARCHAR2(255) not null, SCALE REAL, SYMBOL NVARCHAR2(255));
CREATE TABLE TB_UNIT_TYPE (ID INTEGER PRIMARY KEY not null, CAPTION NVARCHAR2(255), EXP_ELECTRICCURRENT INTEGER(9) default 0 not null, EXP_LENGTH INTEGER(9) default 0 not null, EXP_LUMINOUSINTENSITY INTEGER(9) default 0 not null, EXP_MASS INTEGER(9) default 0 not null, EXP_SUBSTANCEAMOUNT INTEGER(9) default 0 not null, EXP_TEMPERATURE INTEGER(9) default 0 not null, EXP_TIME INTEGER(9) default 0 not null, ID_MAJOR_UNIT INTEGER(18), ID_MINOR_UNIT INTEGER(18), NAME NVARCHAR2(255) not null);
CREATE TABLE TB_HOR_ALIGNMENT_TBD (ID INTEGER PRIMARY KEY not null, SHORT_VALUE VARCHAR2(30), VALUE VARCHAR2(255), DATE_OF_CREATION DATETIME_as_text, DESIGNER VARCHAR2(255), COMMENTARY VARCHAR2(2000), ACTIVE INTEGER(1) default 1, PRIORITY INTEGER(10));
CREATE TABLE TB_VER_ALIGNMENT_TBD (ID INTEGER PRIMARY KEY not null, SHORT_VALUE VARCHAR2(30), VALUE VARCHAR2(255), DATE_OF_CREATION DATETIME_as_text, DESIGNER VARCHAR2(255), COMMENTARY VARCHAR2(2000), ACTIVE INTEGER(1) default 1, PRIORITY INTEGER(10));
CREATE TABLE CONSTRUCT (FID INTEGER PRIMARY KEY not null);
CREATE TRIGGER CONSTRUCT_BI_FID before insert on CONSTRUCT for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into CONSTRUCT (FID)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'));
  select raise(ignore);
end;
CREATE TRIGGER CONSTRUCT_AI_FID after insert on CONSTRUCT for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 1;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 1, current_timestamp, 0);
end;
CREATE TRIGGER CONSTRUCT_BU_FID before update of FID on CONSTRUCT for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class CONSTRUCT cannot be changed.');
end;
CREATE TRIGGER CONSTRUCT_AU_FID after update on CONSTRUCT for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER CONSTRUCT_AD_FID after delete on CONSTRUCT for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
CREATE TABLE CONSTRUCT_LINES (FID INTEGER PRIMARY KEY not null, GEOM FDO_GEOMETRY_as_blob, LENGTH REAL(20,8), DESCRIPTION VARCHAR2(48), FID_PARENT INTEGER(10));
CREATE TRIGGER CONSTRUCT_LINES_AI_FID after insert on CONSTRUCT_LINES for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 2;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 2, current_timestamp, 0);
end;
CREATE TRIGGER CONSTRUCT_LINES_BU_FID before update of FID on CONSTRUCT_LINES for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class CONSTRUCT_LINES cannot be changed.');
end;
CREATE TRIGGER CONSTRUCT_LINES_AU_FID after update on CONSTRUCT_LINES for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER CONSTRUCT_LINES_AD_FID after delete on CONSTRUCT_LINES for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
CREATE TRIGGER CONSTRUCT_LINES_BI_FID before insert on CONSTRUCT_LINES for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into CONSTRUCT_LINES (FID, GEOM, LENGTH, DESCRIPTION, FID_PARENT)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'), new.GEOM, new.LENGTH, new.DESCRIPTION, new.FID_PARENT);
  select raise(ignore);
end;
CREATE TABLE CONSTRUCT_MARKERS (FID INTEGER PRIMARY KEY not null, GEOM FDO_GEOMETRY_as_blob, ORIENTATION REAL(6,3) default 90 not null, Z REAL(20,8), QUALITY INTEGER(10), DESCRIPTION VARCHAR2(48), FID_PARENT INTEGER(10));
CREATE TRIGGER CONSTRUCT_MARKERS_AI_FID after insert on CONSTRUCT_MARKERS for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 3;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 3, current_timestamp, 0);
end;
CREATE TRIGGER CONSTRUCT_MARKERS_BU_FID before update of FID on CONSTRUCT_MARKERS for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class CONSTRUCT_MARKERS cannot be changed.');
end;
CREATE TRIGGER CONSTRUCT_MARKERS_AU_FID after update on CONSTRUCT_MARKERS for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER CONSTRUCT_MARKERS_AD_FID after delete on CONSTRUCT_MARKERS for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
CREATE TRIGGER CONSTRUCT_MARKERS_BI_FID before insert on CONSTRUCT_MARKERS for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into CONSTRUCT_MARKERS (FID, GEOM, ORIENTATION, Z, QUALITY, DESCRIPTION, FID_PARENT)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'), new.GEOM, new.ORIENTATION, new.Z, new.QUALITY, new.DESCRIPTION, new.FID_PARENT);
  select raise(ignore);
end;
CREATE TABLE CONSTRUCT_POINTS (FID INTEGER PRIMARY KEY not null, GEOM FDO_GEOMETRY_as_blob, ORIENTATION REAL(6,3) default 90 not null, Z REAL(20,8), QUALITY INTEGER(10), DESCRIPTION VARCHAR2(48), FID_PARENT INTEGER(10));
CREATE TRIGGER CONSTRUCT_POINTS_AI_FID after insert on CONSTRUCT_POINTS for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 4;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 4, current_timestamp, 0);
end;
CREATE TRIGGER CONSTRUCT_POINTS_BU_FID before update of FID on CONSTRUCT_POINTS for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class CONSTRUCT_POINTS cannot be changed.');
end;
CREATE TRIGGER CONSTRUCT_POINTS_AU_FID after update on CONSTRUCT_POINTS for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER CONSTRUCT_POINTS_AD_FID after delete on CONSTRUCT_POINTS for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
CREATE TRIGGER CONSTRUCT_POINTS_BI_FID before insert on CONSTRUCT_POINTS for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into CONSTRUCT_POINTS (FID, GEOM, ORIENTATION, Z, QUALITY, DESCRIPTION, FID_PARENT)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'), new.GEOM, new.ORIENTATION, new.Z, new.QUALITY, new.DESCRIPTION, new.FID_PARENT);
  select raise(ignore);
end;
CREATE TABLE CONSTRUCT_POINTS_TBL (FID INTEGER PRIMARY KEY not null, GEOM FDO_GEOMETRY_as_blob, LABEL_DEF_ID INTEGER(18), FID_PARENT INTEGER(10), LABEL_TEXT VARCHAR2(2000), HORIZONTAL_ALIGNMENT VARCHAR2(10) default 'Left' not null, VERTICAL_ALIGNMENT VARCHAR2(10) default 'Baseline' not null, ORIENTATION REAL(6,3) default 90 not null, PRE VARCHAR2(255), SUF VARCHAR2(255));
CREATE TRIGGER CONSTRUCT_POINTS_TBL_BI_FID before insert on CONSTRUCT_POINTS_TBL for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into CONSTRUCT_POINTS_TBL (FID, GEOM, LABEL_DEF_ID, FID_PARENT, LABEL_TEXT, HORIZONTAL_ALIGNMENT, VERTICAL_ALIGNMENT, ORIENTATION, PRE, SUF)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'), new.GEOM, new.LABEL_DEF_ID, new.FID_PARENT, new.LABEL_TEXT, new.HORIZONTAL_ALIGNMENT, new.VERTICAL_ALIGNMENT, new.ORIENTATION, new.PRE, new.SUF);
  select raise(ignore);
end;
CREATE TRIGGER CONSTRUCT_POINTS_TBL_AI_FID after insert on CONSTRUCT_POINTS_TBL for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 5;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 5, current_timestamp, 0);
end;
CREATE TRIGGER CONSTRUCT_POINTS_TBL_BU_FID before update of FID on CONSTRUCT_POINTS_TBL for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class CONSTRUCT_POINTS_TBL cannot be changed.');
end;
CREATE TRIGGER CONSTRUCT_POINTS_TBL_AU_FID after update on CONSTRUCT_POINTS_TBL for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER CONSTRUCT_POINTS_TBL_AD_FID after delete on CONSTRUCT_POINTS_TBL for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
CREATE INDEX CONSTRUCT_POINTS_IX1 on CONSTRUCT_POINTS (FID_PARENT);
CREATE INDEX CONSTRUCT_MARKERS_IX1 on CONSTRUCT_MARKERS (FID_PARENT);
CREATE INDEX CONSTRUCT_LINES_IX1 on CONSTRUCT_LINES (FID_PARENT);
CREATE TABLE TB_FEATURE_GROUP (FID INTEGER PRIMARY KEY not null, GEOM FDO_GEOMETRY_as_blob, ORIENTATION REAL(6,3) default 90 not null, Z REAL(20,8), QUALITY INTEGER(10), DATE_CREATION DATETIME_as_text, FID_TEMPLATE INTEGER(10), IS_MIRROR INTEGER(1), SCALE_FACTOR REAL(20,8), USER_FLAG VARCHAR2(255));
CREATE TRIGGER TB_FEATURE_GROUP_AI_FID after insert on TB_FEATURE_GROUP for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 6;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 6, current_timestamp, 0);
end;
CREATE TRIGGER TB_FEATURE_GROUP_BU_FID before update of FID on TB_FEATURE_GROUP for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class TB_FEATURE_GROUP cannot be changed.');
end;
CREATE TRIGGER TB_FEATURE_GROUP_AU_FID after update on TB_FEATURE_GROUP for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER TB_FEATURE_GROUP_AD_FID after delete on TB_FEATURE_GROUP for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
CREATE TRIGGER TB_FEATURE_GROUP_BI_FID before insert on TB_FEATURE_GROUP for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into TB_FEATURE_GROUP (FID, GEOM, ORIENTATION, Z, QUALITY, DATE_CREATION, FID_TEMPLATE, IS_MIRROR, SCALE_FACTOR, USER_FLAG)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'), new.GEOM, new.ORIENTATION, new.Z, new.QUALITY, new.DATE_CREATION, new.FID_TEMPLATE, new.IS_MIRROR, new.SCALE_FACTOR, new.USER_FLAG);
  select raise(ignore);
end;
CREATE INDEX TB_FEATURE_GROUP_IX1 on TB_FEATURE_GROUP (FID_TEMPLATE);
CREATE TABLE TB_FEATURE_GROUP_FEATURE (FID INTEGER PRIMARY KEY not null, F_CLASS_ID INTEGER(10), FID_FEATURE INTEGER(10), FID_FEATURE_GROUP INTEGER(10), FID_TEMPLATE_FEATURE INTEGER(10), USER_FLAG VARCHAR2(255), DATE_CREATION DATETIME_as_text);
CREATE INDEX TB_FEATURE_GROUP_FEATURE_IX1 on TB_FEATURE_GROUP_FEATURE (FID_FEATURE);
CREATE INDEX TB_FEATURE_GROUP_FEATURE_IX2 on TB_FEATURE_GROUP_FEATURE (FID_FEATURE_GROUP);
CREATE INDEX TB_FEATURE_GROUP_FEATURE_IX3 on TB_FEATURE_GROUP_FEATURE (F_CLASS_ID);
CREATE TRIGGER TB_FEATURE_GROUP_FEATURE_AD_FID after delete on TB_FEATURE_GROUP_FEATURE for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
CREATE TRIGGER TB_FEATURE_GROUP_FEATURE_AI_FID after insert on TB_FEATURE_GROUP_FEATURE for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 7;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 7, current_timestamp, 0);
end;
CREATE TRIGGER TB_FEATURE_GROUP_FEATURE_AU_FID after update on TB_FEATURE_GROUP_FEATURE for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER TB_FEATURE_GROUP_FEATURE_BU_FID before update of FID on TB_FEATURE_GROUP_FEATURE for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class TB_FEATURE_GROUP_FEATURE cannot be changed.');
end;
CREATE TRIGGER TB_FEATURE_GROUP_FEATURE_BI_FID before insert on TB_FEATURE_GROUP_FEATURE for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into TB_FEATURE_GROUP_FEATURE (FID, F_CLASS_ID, FID_FEATURE, FID_FEATURE_GROUP, FID_TEMPLATE_FEATURE, USER_FLAG, DATE_CREATION)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'), new.F_CLASS_ID, new.FID_FEATURE, new.FID_FEATURE_GROUP, new.FID_TEMPLATE_FEATURE, new.USER_FLAG, new.DATE_CREATION);
  select raise(ignore);
end;
CREATE TABLE TEST_CLASSE_01 (FID INTEGER PRIMARY KEY not null);
CREATE TRIGGER TEST_CLASSE_01_BI_FID before insert on TEST_CLASSE_01 for each row
when new.FID = -1
begin
  update TB_SEQUENCE_EMULATION set NEXT_VALUE = NEXT_VALUE+1 where SEQUENCE_NAME = 'TB_UFID_S';
  insert into TEST_CLASSE_01 (FID)
    values ((select NEXT_VALUE-1 from TB_SEQUENCE_EMULATION where SEQUENCE_NAME = 'TB_UFID_S'));
  select raise(ignore);
end;
CREATE TRIGGER TEST_CLASSE_01_AI_FID after insert on TEST_CLASSE_01 for each row
begin
  delete from TB_UFID where FID = new.FID and F_CLASS_ID = 8;
  insert into TB_UFID (FID, F_CLASS_ID, TOUCH_TS, LOCKED)
    values (new.FID, 8, current_timestamp, 0);
end;
CREATE TRIGGER TEST_CLASSE_01_BU_FID before update of FID on TEST_CLASSE_01 for each row
when new.fid != old.fid
begin
  select raise(ROLLBACK, 'FID of feature class TEST_CLASSE_01 cannot be changed.');
end;
CREATE TRIGGER TEST_CLASSE_01_AU_FID after update on TEST_CLASSE_01 for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = new.FID;
end;
CREATE TRIGGER TEST_CLASSE_01_AD_FID after delete on TEST_CLASSE_01 for each row
begin
  update TB_UFID set TOUCH_TS = current_timestamp where FID = old.FID;
end;
